### ISSUE TITLE
Wizard Lightning

### ISSUE THREAD

**Issue by Fortist** [Gaz492/Framland#2]
So, I was in the middle of testing something with a Wizard from Electroblob's Wizardry and he has cast a lightning (Sky lightning) spell and the game crashed with this 

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2019-01-23 14:07:18 EST
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at uk.gaz492.framland.event.FramlandEventHandler.onServerTick(FramlandEventHandler.java:34)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_432_FramlandEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

While I would just give up on this mod, I really actually want RF powered Farmland, though I do not care for the lightning calling part and the Snad naming conventions. Why not "Powered Farms" or at least something different? Anyway, there you go.

**Comment by Gaz492** [comment]
So ive released a new beta version, would you be able to test that this solves the issue you are having https://minecraft.curseforge.com/projects/framland/files/2664870
